AVR2025: IEEE 802.15.4 MAC Reference Manual
Microcontroller Wireless Solutions
pal_board.c File Reference
Detailed Description
PAL board specific functionality.
This file implements PAL board specific functionality.
Id
pal_board.c 24833 2011-01-11 12:39:46Z v_prasad.anjangi
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Definition in file pal_board.c.
Functions
void clock_init (void)
void event_system_init (void)
void gpio_init (void)
void interrupt_system_init (void)
void pal_button_init (void)
button_state_t pal_button_read (button_id_t button_no)
bool pal_calibrate_rc_osc (void)
void pal_led (led_id_t led_no, led_action_t led_setting)
void pal_led_init (void)
void pal_trx_read_timestamp (uint32_t *timestamp)
void pal_wdt_enable (WDT_PER_t period)
void RTC_Initialize (uint16_t period, uint16_t count, uint16_t compareValue, RTC_PRESCALER_t prescaler)
void RTC_SetIntLevels (RTC_OVFINTLVL_t ovfIntLevel, RTC_COMPINTLVL_t compIntLevel)
void sleeping_timer_init (void)
void sleeping_timer_with_wdt (void)
void sleeping_timer_without_wdt (void)
void timer_init_non_generic (void)
void wdt_clear (void)
void wdt_init (void)
void wdt_parallel_timer_init (void)
Function Documentation
void clock_init (void)
Initialize the clock of the ATxmega.
Definition at line 110 of file pal_board.c.
Referenced by pal_init().
void event_system_init (void)
Initialize the event system of the ATxmega.
Definition at line 85 of file pal_board.c.
Referenced by pal_init().
void gpio_init (void)
Initializes the GPIO pins.
This function is used to initialize the port pins used to connect the microcontroller to transceiver.
Definition at line 158 of file pal_board.c.
Referenced by pal_init().
void interrupt_system_init (void)
Initialize the interrupt system of the ATxmega.
Definition at line 99 of file pal_board.c.
Referenced by pal_init().
void pal_button_init (void)
Initialize the button.
Button initialization.
Definition at line 257 of file pal_board.c.
button_state_t pal_button_read (button_id_t button_no)
Read button.
Button handling.
Parameters:
button_no Button ID
Definition at line 270 of file pal_board.c.
References BUTTON_OFF, and BUTTON_PRESSED.
bool pal_calibrate_rc_osc (void)
Calibrates the internal RC oscillator.
This function calibrates the internal RC oscillator.
Returns:
True since the RC oscillator is always calibrated automatically at startup by hardware itself
Definition at line 75 of file pal_board.c.
void pal_led (led_id_t led_no, led_action_t led_setting)
Control LED status.
LED handling.
Parameters:
[in] led_no LED ID
[in] led_setting LED_ON, LED_OFF, LED_TOGGLE
Definition at line 222 of file pal_board.c.
References LED_OFF, LED_ON, and LED_TOGGLE.
void pal_led_init (void)
Initialize LEDs.
LED initialization.
Definition at line 207 of file pal_board.c.
void pal_trx_read_timestamp (uint32_t * timestamp)
Provides timestamp of the last received frame.
This function provides the timestamp (in microseconds) of the last received frame.
Parameters:
[out] Timestamp in microseconds
Definition at line 51 of file pal_board.c.
void pal_wdt_enable (WDT_PER_t period)
Enable Watchdog and set prescaler.
This function enables the Watchdog and applies prescaler settings. The Watchdog will be reset automatically.
The function writes the correct signature to the Configuration Change Protection register before writing the CTRL register. Interrupts are automatically ignored during the change enable period. The function will wait for the watchdog to be synchronized to the other clock domains before proceeding
Parameters:
period Watchdog Timer timeout period
Definition at line 334 of file pal_board.c.
References WDT_IsSyncBusy.
Referenced by wdt_init().
void RTC_Initialize (uint16_t period, uint16_t count, uint16_t compareValue, RTC_PRESCALER_t prescaler)
This function initializes the RTC with period, initial count, compare value and clock prescaler.
All the synchronized registers are written at the same time to save time. The program code need to check if the RTC is busy before calling this function. The RTC_Busy() function can be used to do this.
Parameters:
period RTC period. Topvalue = Period - 1.
count Initial RTC count.
compareValue Compare value.
prescaler Clock prescaler setting.
Note:
It is required that the period of the Sleeping Timer (RTC) is less than the Time-out period of Watchdog Timer (If enabled) to avoid the unintentional reset of the device.
Definition at line 419 of file pal_board.c.
Referenced by sleeping_timer_with_wdt(), and sleeping_timer_without_wdt().
void RTC_SetIntLevels (RTC_OVFINTLVL_t ovfIntLevel, RTC_COMPINTLVL_t compIntLevel)
This function sets both compare and overflow interrupt levels in one go.
Parameters:
ovfIntLevel The overflow interrupt level.
compIntLevel The compare interrupt level.
Definition at line 438 of file pal_board.c.
Referenced by sleeping_timer_with_wdt(), and sleeping_timer_without_wdt().
void sleeping_timer_init (void)
Initialization of sleeping timer (RTC) of the Atxmega1281.
Definition at line 361 of file pal_board.c.
References sleeping_timer_with_wdt(), and sleeping_timer_without_wdt().
Referenced by pal_init().
void sleeping_timer_with_wdt (void)
Initialization of Sleeping timer (RTC) of the Atxmega1281 when Watchdog Timer is enabled. The period for the Sleeping timer should be given by the user in this case and the period of the sleeping timer should be less than the time-out period of the watchdog timer.
Note:
It is required that the period of the Sleeping Timer (RTC) is less than the Time-out period of Watchdog Timer (If enabled) to avoid the unintentional reset of the device.
Definition at line 394 of file pal_board.c.
References RTC_Initialize(), and RTC_SetIntLevels().
Referenced by ISR(), and sleeping_timer_init().
void sleeping_timer_without_wdt (void)
Initialization of Sleeping timer (RTC) of the Atxmega1281 when Watchdog Timer is not enabled. The period for the Sleeping timer should be given by the user in this case.
Definition at line 376 of file pal_board.c.
References RTC_Initialize(), and RTC_SetIntLevels().
Referenced by ISR(), and sleeping_timer_init().
void wdt_clear (void)
Resets the watchdog timer of the ATxmega1281 before it reaches its time-out period.
Definition at line 311 of file pal_board.c.
References pal_timer_start(), TIMEOUT_RELATIVE, and WDT_Reset.
Referenced by ISR(), and wdt_parallel_timer_init().
void wdt_init (void)
Initialize the watchdog timer of the ATxmega1281.
Definition at line 300 of file pal_board.c.
References pal_wdt_enable().
Referenced by pal_init().
void wdt_parallel_timer_init (void)
Parallel Software timer initialization if the Sleeping timer (RTC) is not enabled to reset the Watchdog timer periodically.
Definition at line 350 of file pal_board.c.
References pal_timer_start(), TIMEOUT_RELATIVE, and wdt_clear().
Referenced by pal_init().