ATMEL: hid_task.c File Reference
hid_task.c File Reference
#include "config.h"
#include "conf_usb.h"
#include "hid_task.h"
#include "lib_mcu/usb/usb_drv.h"
#include "usb_descriptors.h"
#include "modules/usb/device_chap9/usb_standard_request.h"
#include "usb_specific_request.h"
#include "lib_mcu/util/start_boot.h"
Functions
void hid_report_out (void)
void hid_report_in (void)
void hid_task_init (void)
void hid_task (void)
void sof_action ()
Variables
volatile U8 cpt_sof = 0
U8 jump_bootloader
U8 g_last_joy = 0
Detailed Description
This file manages the generic HID IN/OUT task.
Compiler: IAR EWAVR and GNU GCC for AVR
Supported devices: AT90USB1287, AT90USB1286, AT90USB647, AT90USB646
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file hid_task.c.
Function Documentation
void hid_report_out (void)
Get data report from Host
Definition at line 96 of file hid_task.c.
References EP_HID_OUT, Is_usb_receive_out, jump_bootloader, Led0_off, Led0_on, Led1_off, Led1_on, Led2_off, Led2_on, Led3_off, Led3_on, Leds_off, start_boot(), Usb_ack_receive_out, Usb_detach, Usb_read_byte, and Usb_select_endpoint.
Referenced by hid_task().
{
   Usb_select_endpoint(EP_HID_OUT);
   if(Is_usb_receive_out())
   {
      //* Read report from HID Generic Demo
      U8 led_state;
      U8 led_number;
      led_state      = Usb_read_byte()&0x0F; // RepportOUT[0] is LEDS value
      led_number     = Usb_read_byte()&0x0F;
      switch (led_number)
      {
         case 1:
            if(led_state)
            {  Led0_on();   }
            else {Led0_off();}
            break;
         case 2:
            if(led_state)
            {  Led1_on();   }
            else {Led1_off();}
            break;
         case 3:
            if(led_state)
            {  Led2_on();   }
            else {Led2_off();}
            break;
         case 4:
            if(led_state)
            {  Led3_on();   }
            else {Led3_off();}
            break;
      }
      Usb_ack_receive_out();
   }
   //** Check if we received DFU mode command from host
   if(jump_bootloader)
   {
      U32 volatile tempo;
      Leds_off();
      Usb_detach();                          // Detach actual generic HID application
      for(tempo=0;tempo<70000;tempo++);      // Wait some time before
      start_boot();                          // Jumping to booltoader
   }
}
void hid_report_in (void)
Send data report to Host
Check for UP event
Definition at line 146 of file hid_task.c.
References EP_HID_IN, g_last_joy, Is_joy_down, Is_joy_left, Is_joy_right, Is_joy_up, Is_usb_write_enabled, Usb_ack_in_ready, Usb_select_endpoint, and Usb_write_byte.
Referenced by hid_task().
{
   U8 joy   =0;
   Usb_select_endpoint(EP_HID_IN);
   if(!Is_usb_write_enabled())
      return;                                // Not ready to send report
   // Build the Joytick report
   if(Is_joy_up()|| Is_joy_down() || Is_joy_right() || Is_joy_left() )
   {
     joy=0x01;
   }
   if(joy==g_last_joy)
      return;                                // Same report then no send report
   g_last_joy=joy;
   // Send report
   Usb_write_byte(g_last_joy);               // Joystick
   Usb_write_byte(GPIOR1);                   // Dummy (not used)
   Usb_write_byte(GPIOR1);                   // Dummy (not used)
   Usb_write_byte(GPIOR1);                   // Dummy (not used)
   Usb_write_byte(GPIOR1);                   // Dummy (not used)
   Usb_write_byte(GPIOR1);                   // Dummy (not used)
   Usb_write_byte(GPIOR1);                   // Dummy (not used)
   Usb_write_byte(GPIOR1);                   // Dummy (not used)
   Usb_ack_in_ready();                       // Send data over the USB
}
void hid_task_init (void)
This function initializes the target board ressources.
Definition at line 75 of file hid_task.c.
References Joy_init, and Leds_init.
{
   Leds_init();
   Joy_init();
}
void hid_task (void)
Entry point of the HID generic communication task This function manages IN/OUT repport management.
Definition at line 84 of file hid_task.c.
References hid_report_in(), hid_report_out(), and Is_device_enumerated.
{
   if(!Is_device_enumerated())          // Check USB HID is enumerated
      return;
   hid_report_out();
   hid_report_in();
}
Variable Documentation
volatile U8 cpt_sof = 0
Definition at line 65 of file hid_task.c.
Referenced by sof_action().
U8 jump_bootloader
Definition at line 69 of file usb_specific_request.c.
Referenced by hid_report_out(), and usb_hid_set_report_feature().
U8 g_last_joy = 0
Definition at line 67 of file hid_task.c.
Referenced by hid_report_in().